apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersdemo-mysql
spec:
  selector:
    matchLabels:
      app: usersdemo-mysql
  template:
    metadata:
      labels:
        app: usersdemo-mysql
    spec:
      containers:
      - name: usersdemo-mysql
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        image: emohammad/usersdemo-mysql:latest
        ports:
        - containerPort: 3306        
